name: PHPStan

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**/*.php"
      - "src/phpstan.neon"
      - "src/composer.lock"
      - "src/package-lock.json"
      - ".github/workflows/phpstan.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number || 'manual' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Laravelのパッケージ検出とオートローダー最適化のために必要
      - name: Create cache directory
        run: mkdir -p bootstrap/cache
        working-directory: ./src

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        working-directory: ./src

      - name: "Restore result cache"
        uses: actions/cache/restore@v5
        with:
          path: src/vendor/phpstan/phpstan/tmp # phpstan.neonのtmpDirと合わせる
          key: "phpstan-result-cache-${{ env.PR_NUMBER }}"
          # 一致するキャッシュの内最新のものを使用する
          restore-keys: |
            phpstan-result-cache-

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github
        working-directory: ./src

      - name: "Save result cache"
        uses: actions/cache/save@v5
        if: ${{ github.event_name == 'pull_request' && !cancelled() }}
        with:
          path: src/vendor/phpstan/phpstan/tmp # phpstan.neonのtmpDirと合わせる
          key: "phpstan-result-cache-${{ env.PR_NUMBER }}"
